# devops: Transformer Deployment

parameters:
  - name: ENV
    displayName: Choose a Working Environment
    default: 'DEV2'
    type: string
    values:
      - 'DEV2'
      - 'STAGE2'
      - 'SHARED'

# Set variables
variables:
  env: ${{ lower(parameters.ENV) }}
  workspace: '/tmp/tf-identify-service-workspace'

trigger:
- none

resources:
  pipelines:
  - pipeline: triggerTest
    source: 'trigger-source-001'
    trigger: true

pool: eland-pool

stages:
- stage: PreTasks
  displayName: Pre Tasks
  jobs:
  - job: init
    displayName: Display the file structure
    steps:
    - script: |
        pwd
        ls -ltrhR
        echo "I am the dependent pipeline triggered by the source pipeline - trigger-source-001"


