
trigger:
- none

pool: eland-pool

resources:
  repositories:
  - repository: tools
    type: github
    endpoint: joehmchiu

steps:
- checkout: self
  path: /tmp/foo
- checkout: github://joehmchiu/arm-mysql-pipeline
  path: /tmp/bar
