
trigger:
- none

pool: eland-pool

# resources:
#   repositories:
#   - repository: arm-pipelines
#     type: github
#     endpoint: joehmchiuGithub

steps:
- checkout: self
  path: /tmp/foo
- checkout: github://joehmchiuGithub/arm-mysql-pipeline
  path: /tmp/bar
