
trigger:
- none

pool: eland-pool

resources:
  repositories:
  - repository: foo
    type: github
    endpoint: joehmchiuGithub
    name: joehmchiu/arm-mysql-pipeline

steps:
- checkout: self
- checkout: foo
  path: /tmp/foo
