
trigger:
- none

pool: eland-pool

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure-connection-manager'
    subscriptionId: 'dafdecca-01a5-4a82-bba0-489c3c47f4d2'
    action: 'DeleteRG'
    resourceGroupName: 'rg-arm-test-001'
    location: 'australiaeast'
