trigger:
- main


pool: eland-pool

variables:
- ${{ if eq(variables['env'], 'dev') }}:
  - group: dev
- ${{ if eq(variables['env'], 'test') }}:
  - group: test

steps:

- script: |
    echo $(env)
    echo $(name)
  displayName: Step 1 - print version and environment

- script: echo $(password)
  displayName: Step 2 - print secret

- script: pwd ENV ${{parameters.environment}}
  displayName: Step 3 - print parameter
  
