parameters:
  - name: ENV
    displayName: Choose a Working Environment
    default: 'DEV2'
    type: string
    values:
      - 'DEV2'
      - 'STAGE2'
      - 'LIVE'
  - name: KEY
    displayName: The Secret Name
    default: 'helloworld'
    type: string

# Set variables
variables:
  env: ${{ lower(parameters.ENV) }}
  key: ${{ lower(parameters.KEY) }}
  
trigger:
- none

pool: eland-pool

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'KV-Service-Connection-003'
    KeyVaultName: 'kv-box-001'
    SecretsFilter: '*'
    RunAsPreJob: true
- task: CmdLine@2
  inputs:
    script: 'echo $(helloworld)'
      # 'echo $($(key)) > secret.txt'
- script: |
    echo $(foobar) > secret.txt
    echo $("helloworld") > secret1.txt
    echo $($(key)) > secret2.txt
    echo $("$(key)") > secret3.txt
    echo $(helloworld) >> secret.txt
    echo $(helloworld)
    echo $("$(key)")
    
- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
