variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool: eland-pool

steps:

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure-connection-manager'
    KeyVaultName: 'kv-box-001'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: 'echo $(helloworld) > secret.txt'

- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
