parameters:
  - name: ENV
    displayName: Choose a Working Environment
    default: 'DEV2'
    type: string
    values:
      - 'DEV2'
      - 'STAGE2'
      - 'LIVE'
  - name: KEY
    displayName: The Secret Name
    default: 'helloworld'
    type: string

# Set variables
variables:
  env: ${{ lower(parameters.ENV) }}
  ${{ if ne(variables['mykey'], '') }}:
    key: $[ variables.mykey ]
  ${{ else }}:
    key: ${{ lower(parameters.KEY) }}
  test: 'test-001'
  
  
trigger:
- none

pool: eland-pool

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'KV-Service-Connection-003'
    KeyVaultName: 'kv-box-001'
    SecretsFilter: '*'
    RunAsPreJob: true
- task: CmdLine@2
  inputs:
    script: 'echo $(helloworld)'
    
- script: |
    echo $(foobar) > secret.txt
    foo='echo "Foo: \$($(key))" >> secret.txt'
    echo $foo
    eval $foo
    echo "helloworld: $(helloworld)" >> secret.txt
    echo $(helloworld)
    echo "Key: $(key)"
    echo "Key: $(key)" >> secret.txt
    echo "Key: $(foo)"
    echo "Key: $(foo)" >> secret.txt

- script: |
    foo="echo 'Test: \$($(test))' >> secret.txt"
    echo $(test-001)
    echo $foo
    eval $foo
    cat secret.txt

- task: CopyFiles@2
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
