variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool: karbon-pool

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-connection-manager'
    subscriptionId: '418f79d8-2c58-4ec6-974c-7ac5d4713848'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-arm-test-001'
    location: 'australiaeast'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'
